### ISSUE TITLE
Automatic column detection

### ISSUE THREAD

**Issue by wojciechAdaszynski** [jillix/csv-to-array#3]
Hey! I thought about implementing automatic column detection to your library. It would be cool to pass a large csv without specifying each columns name. Tell me if you're interested in me implementing this functionality.

**Comment by IonicaBizau** [comment]
Hey @wojciechAdaszynski!

That's a neat idea! `a-csv` already has the [`headers`](https://github.com/jillix/a-csv#parsepath-options-rowhandler) option which parses the headers, so, maybe you can use that one here. :smile: 

Contributions are welcome! :sparkle:
