### ISSUE TITLE
Possible race condition with large input files

### ISSUE THREAD

**Issue by autoboxer** [jillix/csv-to-array#9]
I have a test scaffolding set up for a project I'm working on that can show the bug in `index.js`, which appears when it's ready to call `callback(null, array)` at the bottom of the function.  Even though it seems everything is in order in some cases, the call is never made, and a silent failure occurs.  I found an easy workaround that I believe is elegant enough to include in the main README.md, however, I want to review with the team before I make any suggestions.  Feel free to reach out at jared.j.collier@gmail.com if you'd like to discuss it.

**Comment by IonicaBizau** [comment]
Sorry for late reply. Feel free to submit a pull request with the changes. Thanks!

**Comment by autoboxer** [comment]
I'm confused as to why this was closed.

**Comment by IonicaBizau** [comment]
> I found an easy workaround that I believe is elegant enough to include in the main README.md, however, I want to review with the team before I make any suggestions. 

I was suggesting to open a pull request and we will review it.

**Comment by autoboxer** [comment]
that's what I get for not reading my own comment.  I hate to say it, but I can't remember the workaround anymore.  I'll see if I can find it and will submit a pull request if I do.

**Comment by IonicaBizau** [comment]
No worries! 😄 

If you'll find it, I'm happy to take a look and eventually merge it. The issue may be in `a-csv` (not calling the callback function or something).
